- project:
    name: victorhugojt/recordtec
    merge-mode: squash
    check:
      jobs:
        - recordtec-check
        - recordtec-lint
    gate:
      jobs:
        - recordtec-check
        - recordtec-lint